Sorghum mRNA-seq Analysis
========================================================

```{r}
library(ggplot2)
# load in mrna_raw_data file as a table
setwd("~/hydrogen/sorghum")
raw_data <- read.table("raw_mrna_data", sep=",", header=FALSE)
names(raw_data) <- c("filepath", "rep", "cell", "pair")
```

```{r raw_read_count, fig.width=12, fig.height=8}
# plot bar chart of this "mrna_raw_read_counts.txt"
library(plyr)
setwd("~/hydrogen/sorghum/mrna")
raw_read_count <- read.table("mrna_raw_read_counts.txt", sep="\t", header=FALSE)
names(raw_read_count) <- c("count", "cell", "rep", "pair")

raw_read_count_paired <- ddply(raw_read_count, c("cell", "rep"), transform, sum_count=sum(count))
raw_read_count_paired <- unique( raw_read_count_paired[,c(2,3,5)] )

ggplot(raw_read_count_paired, aes(x=paste(cell,rep), y=sum_count, fill=cell)) +
  geom_bar(stat="identity") +
  ggtitle("Raw read counts") +
  geom_text(aes(label=sum_count, y=sum_count+500000)) +
  labs(x = "Cell and rep") +
  ylim(0,60000000)
```


```{r raw_quality_scores, fig.width=8, fig.height=4}
# plot quality scores
setwd("~/hydrogen/sorghum/mrna")
require("reshape2")

for (i in 1:nrow(raw_data)) {
  cell = raw_data[i,3]
  rep = raw_data[i,2]
  pair = raw_data[i,4]
  raw_read_qualities <- read.table(paste("raw_read_qualities_",cell,"-",rep,"-",pair,".txt",sep=""), sep="\t", header=FALSE)
  names(raw_read_qualities) <- c("base","mean","lower","upper","10%", "90%")
  raw_read_qualities_melt <- melt(raw_read_qualities, id="base")  # convert to long format
  
  c<-ggplot(data=raw_read_qualities_melt, aes(x=base, y=value, colour=variable)) +
      geom_line() + 
      ggtitle(paste("Raw Read Qualities for ",cell," Rep:",rep, " Pair:",pair)) +
      ylim(0,42)
  print(c)
}
```

```{r trimmed_read_count, fig.width=12, fig.height=8}
# plot chart "mrna_trimmed_read_counts.txt"
library(plyr)
setwd("~/hydrogen/sorghum/mrna") # mrna_trimmed_read_counts.txt
trimmed_read_count <- read.table("mrna_trimmed_read_counts.txt", sep="\t", header=FALSE)
names(trimmed_read_count) <- c("count", "cell", "rep", "pair")

trimmed_read_count_paired <- ddply(trimmed_read_count, c("cell", "rep"), transform, sum_count=sum(count))
trimmed_read_count_paired <- unique( trimmed_read_count_paired[,c(2,3,5)] )

ggplot(trimmed_read_count_paired, aes(x=paste(cell,rep), y=sum_count, fill=cell)) +
  geom_bar(stat="identity") +
  ggtitle("Raw read counts") +
  geom_text(aes(label=sum_count, y=sum_count+500000)) +
  labs(x = "Cell and rep") +
  ylim(0,60000000)
```


```{r trimmed_read_lengths, fig.width=8, fig.height=8}
# load the tables of trimmed read lengths
# smoosh together and plot as a bar chart (possibly with log y scale)

setwd("~/hydrogen/sorghum/mrna")

for (i in 1:nrow(raw_data)) {
  cell = raw_data[i,3]
  rep = raw_data[i,2]
  pair = raw_data[i,4]
  trimmed_read_length <- read.table(paste("t_read_length_",cell,"-",rep,"-",pair,".txt",sep=""), sep="\t", header=FALSE)
  names(trimmed_read_length) <- c("length", "count")
  trimmed_read_length$length <- gsub(trimmed_read_length$length, pattern="([0-9]+)-([0-9]+)", replacement="\\1")
  
  c<-ggplot(trimmed_read_length, aes(x=as.numeric(length), y=count)) +
    geom_bar(stat="identity") +
    ggtitle(paste("Trimmed Read Lengths for ",cell," Rep:",rep, " Pair:",pair)) +
    labs(x = "Read Length") +
    ylim(0,2.1e7)
  print(c)
}
```


```{r trimmed_quality_scores, fig.width=8, fig.height=4}
# plot quality scores
setwd("~/hydrogen/sorghum/mrna")
require("reshape2")

for (i in 1:nrow(raw_data)) {
  cell = raw_data[i,3]
  rep = raw_data[i,2]
  pair = raw_data[i,4]
  raw_read_qualities <- read.table(paste("t_read_qualities_",cell,"-",rep,"-",pair,".txt",sep=""), sep="\t", header=FALSE)
  names(raw_read_qualities) <- c("base","mean","lower","upper","10%", "90%")
  raw_read_qualities_melt <- melt(raw_read_qualities, id="base")  # convert to long format
  
  c<-ggplot(data=raw_read_qualities_melt, aes(x=base, y=value, colour=variable)) +
      geom_line() + 
      ggtitle(paste("Trimmed Read Qualities for ",cell," Rep:",rep, " Pair:",pair)) +
      ylim(0,42)
  print(c)
}
```


```{r tpm_corr, fig.width=12, fig.height=12}
# load express outputs

library(reshape2)
library(ggplot2)
setwd("~/hydrogen/sorghum/mrna")
cells = c("BS", "M")
reps = c(1,2,3)
data <- data.frame()

for (i in cells) {
  for (j in reps) {
    file <- paste("cufflinks_express/express_", i, "-", j, "/results.xprs",sep="")
    print(file)
    tmp <- read.table(file, header=T)
    tmp <- tmp[,c(2,15)] # only keep contig name and tpm column
    tmp$sample <- paste(i,"-",j,sep="")
    data <- rbind(data, tmp)
  }
}
tpm_data <- dcast(data, target_id ~ sample, value.var="tpm")

write.table(tpm_data, file="sorghum_mrna.by_transcript.tpm.csv", sep="\t", row.names=FALSE, quote=F)

row.names(tpm_data) <- tpm_data$target_id
tpm_data<-tpm_data[,-c(1)]
correlation <- cor(tpm_data)
melted <- melt(correlation)
ggplot(data=melted, aes_string(x=names(melted)[1], y=names(melted)[2], fill="value")) +
  geom_tile() +
  ggtitle("TPM Correlation Matrix") +
  geom_text(aes(label = round(value, 2))) +
  xlab('') +
  ylab('')
```


```{r eff_count_corr, fig.width=12, fig.height=12}
# load express outputs

library(reshape2)
library(ggplot2)
setwd("~/hydrogen/sorghum/mrna")
cells = c("BS", "M")
reps = c(1,2,3)
data <- data.frame()

for (i in cells) {
  for (j in reps) {
    file <- paste("express_", i, "-", j, "/results.xprs",sep="")
    #print(file)
    tmp <- read.table(file, header=T)
    tmp <- tmp[,c(2,8)]
    tmp$sample <- paste(i,"-",j,sep="")
    data <- rbind(data, tmp)
  }
}
count_data <- dcast(data, target_id ~ sample, value.var="eff_counts")

write.table(count_data, file="sorghum_mrna.by_transcript.eff_counts.csv", sep="\t", row.names=FALSE, quote=F)

row.names(count_data) <- count_data$target_id
counts<-count_data[,-c(1)]
correlation <- cor(counts)
melted <- melt(correlation)
ggplot(data=melted, aes_string(x=names(melted)[1], y=names(melted)[2], fill="value")) +
  geom_tile() +
  ggtitle("Effective Count Correlation Matrix") +
  geom_text(aes(label = round(value, 2))) +
  xlab('') +
  ylab('')
```

Run EBSeq for differential expression analysis on effective count data

```{r ebseq_sorghum}
setwd("~/hydrogen/sorghum/mrna")
library(EBSeq)
# express outputs stored in 'counts' matrix

counts<-counts[-c(rowSums(counts)==0),] # remove rows that are all zeros

mat <- as.matrix(counts)

sizes <- MedianNorm(counts)
#sizes=QuantileNorm(counts, 0.75) # upper-quantile normalisation
sizes

conditions <- as.factor(rep(c("BS", "M"),each=3))

ebOut <- EBTest(Data=mat, Conditions=conditions, sizeFactors=sizes, maxround=40)

posteriorProbs <- GetPPMat(ebOut)

#annotations <- read.table(file="sorghum_annotation.txt",header=F,sep="\t")
#names(annotations) <- c("sorghum_contig", "sorghum")
probs <- data.frame(posteriorProbs)
probs$sorghum <- row.names(probs)
names(probs) <- c("PPEE", "PPDE", "sorghum")

#anno_probs <- merge(probs, annotations, by="sorghum_contig", all.x=T) 

write.table(anno_probs, "ppde_sorghum_mrna.csv", sep="\t",quote=F,row.names=F)

#DEfound=rownames(posteriorProbs)[which(posteriorProbs[,"PPDE"]>=0.95)]

```

MDH
```{r}
# checking out a list of key sorghum genes
# plot bar charts of tpm with standard error bars

library(plyr)
stderr <- function(vector) {
  sd(vector)/sqrt(length(vector))
}

key <- read.table("key_sorghum.txt",header=F, sep="\t")
names(key) <- c("ID", "desc")
head(tpm_data)
pepc <- tpm_data[which(row.names(tpm_data)=="CUFF.25890.2"),] # Sb09g019930.1 CUFF.25890.2 
pepc_melt <- melt(pepc)
pepc_melt$cell <- gsub(pepc_melt$variable, pattern="-[0-9]", replacement="")
  
tpm <- ddply(pepc_melt, .(cell), numcolwise(mean))        # sum columns, grouping by annotation
tpm[which(tpm$cell=="BS"),"stderr"]<-stderr(pepc_melt[which(pepc_melt$cell=="BS"),]$value)
tpm[which(tpm$cell=="M"),"stderr"]<-stderr(pepc_melt[which(pepc_melt$cell=="M"),]$value)

ggplot(data=tpm, aes(x=cell, y=value, fill=cell)) +
  geom_bar(stat="identity") +
  ggtitle("Expression of NADPMDH") +
  #geom_text(aes(label=sum_count, y=sum_count+500000)) +
  labs(x = "Cell") +
  geom_errorbar(aes(ymax=value+stderr,ymin=value-stderr))

```

OMT
```{r}
# checking out a list of key sorghum genes
# plot bar charts of tpm with standard error bars

library(plyr)
stderr <- function(vector) {
  sd(vector)/sqrt(length(vector))
}

key <- read.table("key_sorghum.txt",header=F, sep="\t")
names(key) <- c("ID", "desc")
head(tpm_data)
pepc <- tpm_data[which(row.names(tpm_data)=="CUFF.23063.1"),] # Sb09g019930.1 CUFF.25890.2 
pepc_melt <- melt(pepc)
pepc_melt$cell <- gsub(pepc_melt$variable, pattern="-[0-9]", replacement="")
  
tpm <- ddply(pepc_melt, .(cell), numcolwise(mean))        # sum columns, grouping by annotation
tpm[which(tpm$cell=="BS"),"stderr"]<-stderr(pepc_melt[which(pepc_melt$cell=="BS"),]$value)
tpm[which(tpm$cell=="M"),"stderr"]<-stderr(pepc_melt[which(pepc_melt$cell=="M"),]$value)

ggplot(data=tpm, aes(x=cell, y=value, fill=cell)) +
  geom_bar(stat="identity") +
  ggtitle("Expression of OMT") +
  #geom_text(aes(label=sum_count, y=sum_count+500000)) +
  labs(x = "Cell") +
  geom_errorbar(aes(ymax=value+stderr,ymin=value-stderr))

```


